# Cross.toml configuration for cross-compilation
# This file is used by the 'cross' tool to configure Docker images and build settings

[build.env]
passthrough = [
    "GITHUB_ACTIONS",
    "GITHUB_REF",
    "GITHUB_SHA",
]

[target.aarch64-unknown-linux-gnu]
# Raspberry Pi Zero W and similar ARM64 devices
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"

[target.x86_64-unknown-linux-gnu]
# Standard Linux x86_64 systems
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main"
